<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>NWN_Timer</RootNamespace>
    <OutputType>WinExe</OutputType>
    <!--If you are willing to use platform-specific APIs, use conditional compilation.
    See https://docs.avaloniaui.net/docs/guides/platforms/platform-specific-code/dotnet for more details.-->
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NWN_Timer\NWN_Timer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="notification_chime.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="string_warning_fall.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="string_warning_rise.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
